credentials:
  usernames:
    admin:
      email: jsmith@gmail.com
      logged_in: False # Will be managed automatically
      name: John Smith
      password: admin123 # Will be hashed automatically
    admin1:
      email: rbriggs@gmail.com
      logged_in: False # Will be managed automatically
      name: Rebecca Briggs
      password: admin1123 # Will be hashed automatically
cookie:
  expiry_days: 30
  key: some_signature_key # Must be string
  name: some_cookie_name
preauthorized:
  emails:
  - melsby@gmail.com