credentials:
  usernames:
    admin:
      email: kunalshrivastava.pune@gmail.com
      logged_in: False # Will be managed automatically
      name: Admin
      password: admin123 # Will be hashed automatically
    kunal:
      email: kunalshrivastava.pune@gmail.com
      logged_in: False # Will be managed automatically
      name: kunal
      password: kunal # Will be hashed automatically
    anand:
      email: kunalshrivastava.pune@gmail.com
      logged_in: False # Will be managed automatically
      name: anand
      password: anand # Will be hashed automatically
    rahul:
      email: kunalshrivastava.pune@gmail.com
      logged_in: False # Will be managed automatically
      name: rahul
      password: rahul # Will be hashed automatically

    admin1:
      email: kunalshrivastava.pune@gmail.com
      logged_in: False # Will be managed automatically
      name: Admin
      password: admin1123 # Will be hashed automatically
cookie:
  expiry_days: 30
  key: some_signature_key # Must be string
  name: some_cookie_name1
preauthorized:
  emails:
  - kunalshrivastava.pune@gmail.com