
import pandas as pd
import oracledb
import random
import numpy as np
# Establish connection
connection = oracledb.connect(
    user="admin",
    password="Gudiya@123456",
    dsn="rajaniishdb_high",
    config_dir=r"C:\Tools\Oracle Wallet\Wallet_RAJANIISHDB",
    wallet_location=r"C:\Tools\Oracle Wallet\Wallet_RAJANIISHDB",
    wallet_password="Gudiya@1"
)

# Check connection version
print(connection.version)

# Execute query
cursor = connection.cursor()
cursor.execute("SELECT * from tmp1")

# Fetch all rows
rows = cursor.fetchall()

# Get column names
column_names = [col[0] for col in cursor.description]

# Convert rows to DataFrame
df = pd.DataFrame(rows, columns=column_names)



# Create a table in Oracle from the random DataFrame
cursor = connection.cursor()
try:
    cursor.execute("DROP TABLE random_table")
except:
    pass

cursor.execute("""
    CREATE TABLE random_table (
        id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
        A FLOAT,
        B FLOAT,
        C VARCHAR(1)
    )
""")

random_df = pd.DataFrame({
    'A': np.random.randn(10),
    'B': np.random.rand(10),
    'C': [random.choice(['X', 'Y', 'Z']) for _ in range(10)]
})

# Insert data into the table
for index, row in random_df.iterrows():
    cursor.execute("INSERT INTO random_table (A, B, C) VALUES (:1, :2, :3)", (row['A'], row['B'], row['C']))


connection.commit()











# Close cursor and connection
cursor.close()
connection.close()

# Print DataFrame
print(df)
